### ISSUE TITLE
Up to date JSON schema

### ISSUE THREAD

**Issue by Manu404** [lsmoura/mtgjson#166] opened 2016-05-14 16:47 UTC
I would like to use your db but  I can't find an up-to-date schema, the closest thing I've found is in the sample section with the GO datamodel, but even there some fields are not mapped, for instance mkm_name and mkm_id.

Can you provide a complete up-to-date schema ?

**Comment by Manu404** [comment] 2016-05-14 19:48
For those looking for the same stuffs as me, I've found the schema by developping a small utility. Here's my result: 

===> .block:String
===> .booster.booster:Array<String>
===> .booster:Array<String>
===> .border:String
===> .cards.artist:String
===> .cards.border:String
===> .cards.cmc:Float
===> .cards.cmc:Integer
===> .cards.colorIdentity:Array<String>
===> .cards.colors:Array<String>
===> .cards.flavor:String
===> .cards.foreignNames.language:String
===> .cards.foreignNames.multiverseid:Integer
===> .cards.foreignNames.name:String
===> .cards.hand:Integer
===> .cards.id:String
===> .cards.imageName:String
===> .cards.layout:String
===> .cards.legalities.format:String
===> .cards.legalities.legality:String
===> .cards.life:Integer
===> .cards.loyalty:Integer
===> .cards.manaCost:String
===> .cards.mciNumber:String
===> .cards.multiverseid:Integer
===> .cards.name:String
===> .cards.names:Array<String>
===> .cards.number:String
===> .cards.originalText:String
===> .cards.originalType:String
===> .cards.power:String
===> .cards.printings:Array<String>
===> .cards.rarity:String
===> .cards.releaseDate:String
===> .cards.reserved:Boolean
===> .cards.rulings.date:String
===> .cards.rulings.text:String
===> .cards.source:String
===> .cards.starter:Boolean
===> .cards.subtypes:Array<String>
===> .cards.supertypes:Array<String>
===> .cards.text:String
===> .cards.timeshifted:Boolean
===> .cards.toughness:String
===> .cards.type:String
===> .cards.types:Array<String>
===> .cards.variations:Array<Integer>
===> .cards.watermark:String
===> .code:String
===> .gathererCode:String
===> .magicCardsInfoCode:String
===> .magicRaritiesCodes:Array<String>
===> .mkm_id:Integer
===> .mkm_name:String
===> .name:String
===> .oldCode:String
===> .onlineOnly:Boolean
===> .releaseDate:String
===> .translations.cn:String
===> .translations.de:String
===> .translations.es:String
===> .translations.fr:String
===> .translations.it:String
===> .translations.jp:String
===> .translations.ko:String
===> .translations.pt:String
===> .translations.ru:String
===> .translations.tw:String
===> .translations.zh-hans:String
===> .translations.zh-hant:String
===> .type:String

**Comment by starryknight64** [comment] 2016-05-20 16:07
This looks like a duplicate of #71.

**Comment by lsmoura** [comment] 2016-05-20 19:23
This is a duplicate of #71,like @starryknight64 said. I'll be closing this, but thanks for that list, @Manu404 .

**Closed by lsmoura** 2016-05-20 19:23 UTC
